dist: bionic
language: elixir
elixir: '1.9.1'
otp_release: '22.1'

services:
  - postgresql

before_install:
  - sudo apt-get install ldap-utils slapd

before_script:
  - psql -U postgres -c "create user inkfish with password 'oobeiGait3ie' createdb"
  - bash test/setup.sh
